import { Crystal } from '../types';

// Rich sample dataset for the demo workspace.
// Notes reference each other via linkedNoteIds so the graph immediately
// shows clusters and connections — users see the value within seconds.

const now = Date.now();
const DAY = 86_400_000;

export const DEMO_NOTES: Crystal[] = [
  {
    id: 'demo-1',
    title: 'Product roadmap for Q3 launch',
    content: 'Key milestones: onboarding redesign, search v2, mobile launch.',
    body: 'We need to prioritize the onboarding redesign first because first-time activation is our biggest drop-off. Then ship search improvements and finally target the mobile App Store launch by end of Q3.',
    type: 'task',
    timestamp: '9:15 AM',
    createdAt: now - DAY * 2,
    updatedAt: now - DAY * 2,
    pinned: true,
    mood: 'Focused',
    moodColor: '#3b82f6',
    tags: ['BUSINESS', 'STARTUP'],
    topics: ['product', 'roadmap', 'launch'],
    linkedNoteIds: ['demo-2', 'demo-3'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
  {
    id: 'demo-2',
    title: 'Voice interface changes everything about note-taking',
    content: 'Speaking is 3x faster than typing — users capture more context.',
    body: 'The key insight from user research: people have 3x more thoughts than they ever write down. The friction of typing causes them to filter out nuance. Voice removes that barrier. This is the core value proposition.',
    type: 'idea',
    timestamp: '11:42 AM',
    createdAt: now - DAY * 4,
    updatedAt: now - DAY * 4,
    mood: 'Creative',
    moodColor: '#8b5cf6',
    tags: ['IDEAS', 'RESEARCH'],
    topics: ['voice', 'product insight', 'user behavior'],
    linkedNoteIds: ['demo-1', 'demo-4', 'demo-5'],
    connections: 3,
    flashcardEnabled: true,
    flashcardReview: {
      nextReviewAt: now - DAY,
      interval: 1,
      easeFactor: 2.5,
      totalReviews: 0,
      repetition: 0,
    },
    version: 'v2',
  },
  {
    id: 'demo-3',
    title: 'Weekly team sync — activation metrics',
    content: 'Day-7 retention at 34%. Goal is 45% by month end.',
    body: 'Discussed activation metrics in the team sync. Current day-7 retention is 34% which is below our 45% target. Main theories: (1) empty state on first launch, (2) no guidance for the graph feature, (3) flashcard discovery too buried.',
    type: 'event',
    timestamp: '3:00 PM',
    createdAt: now - DAY * 1,
    updatedAt: now - DAY * 1,
    mood: 'Neutral',
    moodColor: '#6b7280',
    tags: ['BUSINESS', 'DATA'],
    topics: ['retention', 'metrics', 'activation'],
    linkedNoteIds: ['demo-1', 'demo-6'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
  {
    id: 'demo-4',
    title: 'Reading: "Building a Second Brain" by Tiago Forte',
    content: 'PARA method — Projects, Areas, Resources, Archive.',
    body: 'Finished the book. Key takeaway: the PARA method works best when capture is effortless. The bottleneck is always getting information IN, not organizing it. VoiceAction solves exactly this problem. The graph is our version of the connected archive.',
    type: 'text',
    timestamp: '8:20 PM',
    createdAt: now - DAY * 6,
    updatedAt: now - DAY * 6,
    mood: 'Reflective',
    moodColor: '#22c55e',
    tags: ['LEARNING', 'BOOKS'],
    topics: ['second brain', 'knowledge management', 'PARA'],
    linkedNoteIds: ['demo-2', 'demo-5'],
    connections: 2,
    flashcardEnabled: true,
    flashcardReview: {
      nextReviewAt: now - DAY * 2,
      interval: 3,
      easeFactor: 2.5,
      totalReviews: 2,
      repetition: 2,
    },
    version: 'v2',
  },
  {
    id: 'demo-5',
    title: 'Morning reflection: what clarity actually feels like',
    content: 'When the mind is empty of noise, ideas flow without effort.',
    body: 'Had a clear morning after journaling for 20 minutes. Noticed that when I write down everything in my head first — even trivial things — the space that opens up allows genuinely new ideas to emerge. This is why capture matters before organization.',
    type: 'voice',
    timestamp: '7:05 AM',
    createdAt: now - DAY * 3,
    updatedAt: now - DAY * 3,
    mood: 'Calm',
    moodColor: '#06b6d4',
    tags: ['PERSONAL', 'MINDSET'],
    topics: ['clarity', 'journaling', 'creativity'],
    linkedNoteIds: ['demo-2', 'demo-4'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
  {
    id: 'demo-6',
    title: 'Competitor analysis — Notion vs Obsidian vs Mem',
    content: 'None solve the capture friction problem. VoiceAction is unique.',
    body: 'Notion: powerful but complex. Obsidian: great graph but zero capture flow. Mem: decent AI but no voice. The gap in the market is exactly what we are building: effortless capture + intelligent connections. Nobody does both well.',
    type: 'idea',
    timestamp: '2:30 PM',
    createdAt: now - DAY * 5,
    updatedAt: now - DAY * 5,
    mood: 'Energetic',
    moodColor: '#f59e0b',
    tags: ['STARTUP', 'RESEARCH'],
    topics: ['competition', 'market', 'positioning'],
    linkedNoteIds: ['demo-3', 'demo-7'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
  {
    id: 'demo-7',
    title: 'Design principle: reduce cognitive load at every step',
    content: 'One action per screen. One question per moment.',
    body: 'Every extra decision we ask users to make is friction we added. The best interfaces are invisible. They anticipate the next step. Applied to VoiceAction: the mic button should always be the most obvious thing on screen. Everything else should be discoverable, not demanded.',
    type: 'idea',
    timestamp: '4:15 PM',
    createdAt: now - DAY * 7,
    updatedAt: now - DAY * 7,
    mood: 'Creative',
    moodColor: '#8b5cf6',
    tags: ['IDEAS', 'DESIGN'],
    topics: ['design', 'UX principles', 'simplicity'],
    linkedNoteIds: ['demo-6', 'demo-8'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
  {
    id: 'demo-8',
    title: 'Habit stack: capture → review → connect',
    content: 'Daily review of yesterday\'s notes takes 4 minutes. Worth it.',
    body: 'The system that works: capture throughout the day (voice), quick 4-minute review each morning, weekly graph exploration to find connections. This three-step rhythm builds a genuine knowledge base over time. Start with capture. Everything else follows.',
    type: 'task',
    timestamp: '6:00 AM',
    createdAt: now - DAY * 8,
    updatedAt: now - DAY * 8,
    mood: 'Focused',
    moodColor: '#3b82f6',
    tags: ['PERSONAL', 'HABITS'],
    topics: ['habits', 'review', 'knowledge system'],
    linkedNoteIds: ['demo-7', 'demo-5'],
    connections: 2,
    flashcardEnabled: false,
    version: 'v2',
  },
];

export const DEMO_WORKSPACE_KEY = 'va_demo_workspace_loaded';

export function isDemoLoaded(): boolean {
  return localStorage.getItem(DEMO_WORKSPACE_KEY) === 'true';
}

export function markDemoLoaded(): void {
  localStorage.setItem(DEMO_WORKSPACE_KEY, 'true');
}
